[package]
name = "hermes-relayer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
cosmwasm-std.workspace = true

cw-orch-interchain-core = { workspace = true }
cw-orch-interchain-daemon = { workspace = true }
cw-orch-networks = { workspace = true }
cw-orch-core = { workspace = true }
cw-orch-traits = { workspace = true }
cw-orch-daemon = { workspace = true }


hdpath = "0.6.3"
ibc-relayer = { workspace = true }
ibc-relayer-cli = "1.9.0"
ibc-relayer-types = { workspace = true }
tokio.workspace = true
log.workspace = true
cosmrs.workspace = true
futures = "0.3.30"
tonic.workspace = true
futures-util = "0.3.30"
async-recursion = "1.1.1"
serde_json.workspace = true
prost-types = { workspace = true }

[dev-dependencies]
cw-orch = { workspace = true, features = ["daemon"] }
cw-orch-interchain = { workspace = true, features = ["daemon"] }
dotenv = "0.15.0"
ibc-proto = "0.47.0"
pretty_env_logger = "0.5.0"
