[workspace]
members = ["boot-core", "packages/*"]

[workspace.package]
authors    = ["CyberHoward <cyberhoward@protonmail.com>"]
edition    = "2021"
license    = "GPL-3.0-only"
repository = "https://github.com/Abstract-OS/BOOT"

[workspace.dependencies]
cosmwasm-std  = { version = "1.1" }
cw-multi-test = { version = "0.16.0" }
anyhow        = "1.0"
serde         = { version = "1.0.103", default-features = false, features = ["derive"] }

[patch.crates-io]
boot-contract-derive = { git="https://github.com/Kayanski/BOOT.git", branch="feature/new-contract-interface"  }
boot-fns-derive = { git="https://github.com/Kayanski/BOOT.git", branch="feature/new-contract-interface"  }


[patch."https://github.com/Kayanski/BOOT.git"]
boot-contract-derive = { path="packages/boot-contract-derive"  }
boot-fns-derive = { path="packages/boot-fns-derive" }