[workspace]
members = [
  "cw-orch",
  "cw-orch-daemon",
  "cw-orch-environment",
  "cw-orch-mock",
  "packages/*",
  "contracts/*",
]
version = "0.13.3"
resolver = "2"

[workspace.package]
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/AbstractSDK/cw-orchestrator"

[workspace.dependencies]
cw-utils = { version = "1.0.1" }
cosmwasm-std = { version = "1.1" }
cw-multi-test = { version = "0.16.4" }
cw20 = { git = "https://github.com/AbstractSDK/cw-plus.git" }
cw20-base = { git = "https://github.com/AbstractSDK/cw-plus.git" }

# Test Tube env deps
osmosis-test-tube = { version = "16.0.1" }

anyhow = "1.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw-orch-daemon = { path = "cw-orch-daemon" }
cw-orch-environment = { path = "cw-orch-environment" }
cw-orch-mock = { path = "cw-orch-mock" }
thiserror = { version = "1.0.21" }
sha256 = { version = "1.2.1" }
serde_json = "1.0.79"
# Test deps
speculoos = "0.11.0"

# Logging
log = "0.4.14"
