[workspace]
members = ["cw-orchestrate", "packages/*"]

[workspace.package]
authors    = ["CyberHoward <cyberhoward@protonmail.com>"]
edition    = "2021"
license    = "GPL-3.0-only"
repository = "https://github.com/AbstractSDK/cw-orchestrate"

[workspace.dependencies]
cosmwasm-std  = { version = "1.1" }
cw-multi-test = { version = "0.16.4" }
anyhow        = "1.0"
serde         = { version = "1.0.103", default-features = false, features = ["derive"] }

[patch.crates-io]
cw-orchestrate-contract-derive = { path="packages/cw-orchestrate-contract-derive"  }
cw-orchestrate-fns-derive = { path="packages/cw-orchestrate-fns-derive" }
