[workspace]
members = [
  "cw-orch",
  "cw-orch-daemon",
  "cw-orch-interchain",
  "packages/cw-orch-core",
  "packages/cw-orch-mock",
  "packages/cw-orch-networks",
  "packages/cw-orch-osmosis-test-tube",
  "packages/cw-orch-neutron-test-tube",
  "packages/cw-orch-traits",
  "contracts/*",
  "packages/macros/*",
  "packages/interchain/*",
]
resolver = "2"

[workspace.package]
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/AbstractSDK/cw-orchestrator"

[workspace.dependencies]
cw-utils = { version = "1.0.1" }
cosmwasm-std = { version = "1.1" }
cw-multi-test = { package = "abstract-cw-multi-test", version = "1.0.0", features = [
  "cosmwasm_1_4",
] }
cw20 = { package = "abstract-cw20", version = "1.2.2" }
cw20-base = { package = "abstract-cw20-base", version = "1.2.2" }

osmosis-test-tube = { version = "25.0.0" }
neutron-test-tube = { version = "4.0.0" }
margined-neutron-std = { version = "4.0.0" }

anyhow = "1.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
tokio = { version = "1.4", features = ["full"] }

cw-orch = { path = "./cw-orch", version = "0.24.1" }
cw-orch-daemon = { path = "./cw-orch-daemon", version = "0.24.3" }
cw-orch-core = { path = "packages/cw-orch-core", version = "1.2.2" }
cw-orch-traits = { path = "packages/cw-orch-traits", version = "0.23.3" }
cw-orch-mock = { path = "packages/cw-orch-mock", version = "0.23.1" }
cw-orch-networks = { path = "packages/cw-orch-networks", version = "0.23.3" }

# Macros
cw-orch-contract-derive = { path = "packages/macros/cw-orch-contract-derive", version = "0.21.0" }
cw-orch-fns-derive = { path = "packages/macros/cw-orch-fns-derive", version = "0.22.0" }

# Extensions
cw-orch-osmosis-test-tube = { version = "0.3.0", path = "packages/cw-orch-osmosis-test-tube" }

# Interchain
cw-orch-interchain = { path = "cw-orch-interchain", version = "0.3.1" }
cw-orch-interchain-core = { path = "packages/interchain/interchain-core", version = "0.4.1" }
cw-orch-interchain-daemon = { path = "packages/interchain/interchain-daemon", version = "0.4.1" }
cw-orch-interchain-mock = { path = "packages/interchain/interchain-mock", version = "0.4.1" }
cw-orch-starship = { path = "packages/interchain/starship", version = "0.4.1" }
cw-orch-proto = { path = "packages/interchain/proto", version = "0.4.1" }

#Clone Testing
cw-orch-clone-testing = { version = "0.6.1", path = "packages/clone-testing" }

thiserror = { version = "1.0.21" }
sha2 = { version = "0.10.8" }
serde_json = "1.0.79"
tonic = { version = "0.10.2" }
prost-types = "0.12.3"
prost = "0.12.3"
cosmrs = { version = "0.15.0" }
# Test deps
speculoos = "0.11.0"

# Logging
log = "0.4.14"

# Interchain
ibc-relayer-types = { version = "0.25.0" }
ibc-chain-registry = { version = "0.25.0" }

[patch.crates-io]
cw-orch-core = { path = "packages/cw-orch-core" }
