[workspace]
members = ["cw-orch", "packages/*", "contracts/*"]
version = "0.11.2"

[workspace.package]
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/AbstractSDK/cw-orchestrator"

[workspace.dependencies]
cosmwasm-std = { version = "1.1" }
cw-multi-test = { version = "0.16.4" }
anyhow = "1.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
