[workspace]
members = [
    "boot-core",
    "boot-cw-plus",
    "packages/*",
    # "template"
]

[workspace.package]
version = "0.1.3"
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Abstract-OS/BOOT"

[workspace.dependencies]
cw-multi-test = { version = "0.15.0"}
anyhow = "1.0"
boot-contract-derive = {path = "packages/boot-contract-derive", version = "0.1.3"}
