[workspace]
members = ["cw-orch", "cw-orch-daemon", "packages/*", "contracts/*"]
resolver = "2"

[workspace.package]
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/AbstractSDK/cw-orchestrator"

[workspace.dependencies]
cw-utils = { version = "1.0.1" }
cosmwasm-std = { version = "1.1" }
cw-multi-test = { package = "abstract-cw-multi-test", version = "1.0.0", features = [
  "cosmwasm_1_4",
] }
cw20 = { package = "abstract-cw20", version = "1.2.2" }
cw20-base = { package = "abstract-cw20-base", version = "1.2.2" }

# Test Tube env deps. We use git dependencies because the crates.io version recompiles every time
osmosis-test-tube = { version = "24.0.1" }


anyhow = "1.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

cw-orch-daemon = { path = "./cw-orch-daemon", version = "0.21.0" }
cw-orch-core = { path = "packages/cw-orch-core", version = "0.21.1" }
cw-orch-traits = { path = "packages/cw-orch-traits", version = "0.21.0" }
cw-orch-mock = { path = "packages/cw-orch-mock", version = "0.21.0" }
cw-orch-contract-derive = { path = "packages/cw-orch-contract-derive", version = "0.20.0" }
cw-orch-fns-derive = { path = "packages/cw-orch-fns-derive", version = "0.18.0" }
cw-orch-networks = { path = "packages/cw-orch-networks", version = "0.20.0" }

thiserror = { version = "1.0.21" }
sha2 = { version = "0.10.8" }
serde_json = "1.0.79"
tonic = { version = "0.10.2" }
prost-types = "0.12.3"
prost = "0.12.3"
# Test deps
speculoos = "0.11.0"

ibc-chain-registry = { version = "0.25.0" }

# Logging
log = "0.4.14"
