[package]
name = "cw-orch-traits"
version = "0.16.2"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "README.md"


[dependencies]
cw-orch-core = { workspace = true }
prost-types = "0.11.0"
prost = "0.12.1"
