[package]
name = "cw-orch-traits"
version = "0.18.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "README.md"


[dependencies]
cw-orch-core = { workspace = true }
prost-types = { version = "0.11.9" }
prost = { version = "0.11.9" }
