[package]
name = "cw-orch-traits"
version = "0.21.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "README.md"


[dependencies]
cw-orch-core = { workspace = true }
# Prost and Prost-types were kept at 0.11.9 here, because osmosis-test-tube doesn't support prost above 0.11.9
prost-types = { workspace = true }
prost = { workspace = true }
