[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
edition     = { workspace = true }
keywords    = ["cosmwasm", "blockchain"]
license     = { workspace = true }
name        = "cw-orch-traits"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.25.0"


[dependencies]
cw-orch-core = { workspace = true }
prost-types  = { workspace = true }
