[package]
name = "boot-contract-derive"
version = "0.10.0"
authors = { workspace = true}
edition = { workspace = true}
license = { workspace = true}
repository = { workspace = true}
description = "Attribute macro for creating a contract interface."

[lib]
proc-macro = true

[features]
default=["outside_contract"]
outside_contract=[]

[dependencies]
convert_case = "0.6.0"
cosmwasm-std.workspace = true
cw-multi-test.workspace = true
log = "0.4.17"
quote = "1"
schemars = "0.8.12"
serde.workspace = true
syn = { version = "1", features = ["full", "extra-traits"] }
