[package]
name = "boot-contract-derive"
version = "0.10.0"
authors = { workspace = true}
edition = { workspace = true}
license = { workspace = true}
repository = { workspace = true}
description = "Attribute macro for creating a contract interface."

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }