[package]
name = "boot-contract-derive"
version = "0.1.0"
edition = "2021"
authors = ["CyberHoward"]
description = "Attribute macro for creating a BOOTable contract."

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }