[package]
name = "cw-orch-contract-derive"
version = "0.11.0-alpha.1"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Attribute macro for creating a contract interface."

[lib]
proc-macro = true

[features]
propagate_daemon = []

[dependencies]
convert_case = "0.6.0"
log = "0.4.17"
quote = "1"
schemars = "0.8.12"
syn = { version = "1", features = ["full", "extra-traits"] }
