[package]
name = "cw-orch-mock"
version = { workspace = true }
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Adapter for interacting with cw-multi-test via the cw-orchestrator tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-core = { workspace = true }
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
cw-utils = { workspace = true }
serde = { workspace = true }
cosmrs = "0.14.0"

[dev-dependencies]
speculoos = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
