[package]
name = "cw-orch-mock"
version = "0.24.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Adapter for interacting with cw-multi-test via the cw-orchestrator tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-core = { workspace = true }
cosmwasm-std = { workspace = true, features = ["cosmwasm_1_2"] }
cw-multi-test = { workspace = true }
cw-utils = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
log = { workspace = true }

[dev-dependencies]
speculoos = { workspace = true }
# Should be able to replace with workspace cw20 when abstract-cw-plus fork updates to CosmWasm 2
cw20 = { version = "2.0.0" }
cw20-base = { version = "2.0.0" }

mock-contract = { path = "../../contracts-ws/contracts/mock_contract" }
anyhow = { workspace = true }
