[package]
name = "cw-orch-on-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cw-orch-core = { workspace = true }
cosmwasm-std = { workspace = true }
serde.workspace = true
thiserror.workspace = true
cw-storage-plus.workspace = true
