[package]
name = "cw-orch-core"
version = "1.2.3"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "README.md"

exclude = [".env"]

[package.metadata.docs.rs]
# passes all-features to cargo when building the docs.
all-features = true

[features]
default = []
eth = ["dep:snailquote"]

[dependencies]
thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
cw-multi-test = { workspace = true }

log = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }


# Ethereum deps
snailquote = { version = "0.3.1", optional = true }
dirs = "5.0.1"
cw-utils = { workspace = true }
cosmos-sdk-proto = { version = "0.21.1", default-features = false, features = [
  "cosmwasm",
] }
cw-storage-plus = "1.2.0"

[dev-dependencies]
speculoos = { workspace = true }
anyhow = { workspace = true }
