[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
edition     = { workspace = true }
keywords    = ["cosmwasm", "blockchain"]
license     = { workspace = true }
name        = "cw-orch-core"
readme      = "README.md"
repository  = { workspace = true }
version     = "2.1.4"

exclude = [".env"]

[package.metadata.docs.rs]
# passes all-features to cargo when building the docs.
all-features = true

[features]
default = []
eth     = ["dep:snailquote"]

[dependencies]
cosmwasm-std  = { workspace = true }
cw-multi-test = { workspace = true }
serde         = { workspace = true }
thiserror     = { workspace = true }

anyhow     = { workspace = true }
log        = { workspace = true }
serde_json = { workspace = true }
sha2       = { workspace = true }


# Ethereum deps
cosmos-sdk-proto = { workspace = true, features = ["cosmwasm"] }
cw-storage-plus  = { workspace = true }
cw-utils         = { workspace = true }
dirs             = "5.0.1"
snailquote       = { version = "0.3.1", optional = true }

[dev-dependencies]
anyhow    = { workspace = true }
speculoos = { workspace = true }
