[package]
name = "cw-orch-core"
version = "2.1.2"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "README.md"

exclude = [".env"]

[package.metadata.docs.rs]
# passes all-features to cargo when building the docs.
all-features = true

[features]
default = []
mock = ["dep:cw-multi-test"]
eth = ["dep:snailquote"]

[dependencies]
thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }

log = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }


# Ethereum deps
snailquote = { version = "0.3.1", optional = true }
dirs = "5.0.1"
cw-utils = { workspace = true }
cosmos-sdk-proto = { workspace = true, features = ["cosmwasm"] }
cw-storage-plus = { workspace = true }

# Mock Specific Deps
cw-multi-test = { workspace = true, optional = true }


[dev-dependencies]
speculoos = { workspace = true }
anyhow = { workspace = true }
