[package]
name = "proto"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cosmos-sdk-proto = "0.19.0"
cosmrs = "0.14.0"
cosmwasm-std = "1.3.3"
cw-orch = {workspace=true, features=["interchain", "starship"]}
ibc-relayer-types = "0.25.0"
log.workspace = true
prost = "0.11.9"
tokio = "1.32.0"
