[package]
authors     = { workspace = true }
description = "Attribute macro for creating a contract interface."
edition     = { workspace = true }
license     = { workspace = true }
name        = "cw-orch-contract-derive"
repository  = { workspace = true }
version     = "0.21.1"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
quote        = "1"
syn          = { version = "2", features = ["full", "extra-traits"] }
