[package]
authors     = { workspace = true }
description = "Derive macro for generating contract interfaces."
edition     = { workspace = true }
license     = { workspace = true }
name        = "cw-orch-fns-derive"
repository  = { workspace = true }
version     = "0.23.1"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2  = "1"
quote        = "1"
syn          = { version = "2", features = ["full", "extra-traits", "visit-mut"] }
