[package]
name = "cw-orch-proto"
description = "A helper crate for interaction with protos from different chains. Mostly used for handling cw20 coins and ibc transfers"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-interchain-core = { workspace = true }
cw-orch-traits = { workspace = true }
cw-orch-core = { workspace = true }

anyhow = { workspace = true }

ibc-proto = { workspace = true }
prost-types = { workspace = true }
prost = { workspace = true }
cosmwasm-std = { workspace = true }
ibc-relayer-types = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
osmosis-std = { version = "0.26.0" }

[dev-dependencies]
cw-orch-starship = { workspace = true }
cw-orch-interchain-daemon = { workspace = true }
env_logger = "0.11.5"
speculoos = { workspace = true }
