[package]
name = "cw-orch-interchain-daemon"
version = "0.9.0"
description = "An interchain intergration crate for interacting with actual chain nodes (via gRPC)"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-daemon = { workspace = true }
cw-orch-core = { workspace = true }

async-recursion = "1.1.1"
base64 = "0.22.1"
cosmwasm-schema = "2.1.3"
futures = "0.3.30"
ibc-relayer-types = { workspace = true }
log = "0.4.22"
log4rs = "1.3.0"
thiserror = "1.0.63"
tonic = { workspace = true }
cosmrs = { workspace = true }
futures-util = "0.3.30"
derive_builder = "0.20.0"
diff-struct = "0.5.3"
serde_json = { workspace = true }

cw-orch-interchain-core = { workspace = true, features = ["daemon"] }
cw-orch-starship = { workspace = true }
dialoguer = "0.11.0"
cosmwasm-std = { workspace = true }
async-std = "1.13.0"

[dev-dependencies]

pretty_env_logger = "0.5.0"
anyhow = { workspace = true }
cw-orch = { workspace = true, features = ["daemon"] }
cw-orch-interchain = { path = "../../../cw-orch-interchain", features = [
  "daemon",
] }
