[package]
name = "cw-orch"
version = "0.16.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "../README.md"

exclude = [".env"]

[package.metadata.docs.rs]
# passes all-features to cargo when building the docs.
all-features = true

[[example]]
name = "mock_test"

[[example]]
name = "daemon_test"
required-features = ["daemon"]

[[example]]
name = "osmosis_test_tube"
required-features = ["osmosis-test-tube"]

[[example]]
name = "injective"
required-features = ["eth"]

[[example]]
name = "bank_query"
path = "examples/queries/bank_query.rs"
require-features = ["daemon"]

[features]
default = []
# enable the optional dependencies
daemon = [
  "dep:tokio",
  # "dep:tonic",
  "dep:cosmrs",
  "dep:cw-orch-daemon",
]
eth = ["daemon", "cw-orch-core/eth", "cw-orch-daemon?/eth"]
osmosis-test-tube = ["dep:osmosis-test-tube"]

[dependencies]
# Default deps
cw-orch-contract-derive = { workspace = true }
cw-orch-fns-derive = { workspace = true }

cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
cw-multi-test = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
schemars = "0.8.10"
log = { workspace = true }
thiserror = { workspace = true }

# Daemon deps
cw-orch-daemon = { workspace = true, optional = true }
cw-orch-networks = { workspace = true }
tokio = { version = "1.4", features = ["full"], optional = true }
cosmrs = { version = "0.14.0", features = [
  "dev",
  "cosmwasm",
  "grpc",
], optional = true }

# Live mock deps
tonic = { version = "0.9.2", optional = true, features = ["tls", "tls-roots"] }

# Test Tube env deps
osmosis-test-tube = { workspace = true, optional = true }
osmosis-std = { version = "=0.19.1" }
# Env deps
cw-orch-core = { workspace = true }
cw-orch-traits = { workspace = true }
cw-orch-mock = { workspace = true }

[dev-dependencies]
cw-orch = { features = ["daemon"], path = "." }
uid = "0.1.7"
env_logger = "0.10.0"
cosmwasm-schema = "1.2"
tokio-test = "0.4.2"
speculoos = { workspace = true }
ctor = "0.2.0"
duct = "0.13"
counter-contract = { path = "../contracts/counter", features = ["interface"] }
mock-contract = { path = "../contracts/mock_contract", features = [
  "interface",
] }
mock-contract-u64 = { path = "../contracts/mock_contract_u64", features = [
  "interface",
] }
serial_test = "2.0.0"
ibc-relayer-types = { workspace = true }
serde_json = { workspace = true }
# Ethereum deps
ethers-signers = { version = "2.0.7" }
ethers-core = { version = "2.0.7" }
cw20-base = { workspace = true }
cw20 = { workspace = true }
