[package]
name = "cw-orch"
version = "0.13.3"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "../README.md"

exclude = [".env"]

[package.metadata.docs.rs]
# passes all-features to cargo when building the docs.
all-features = true

[[example]]
name = "mock_test"

[[example]]
name = "daemon_test"
required-features = ["daemon"]

[features]
default = []
# enable node-backed tests (ensure Docker is running)
# run with `cargo test --jobs 1 --features node-tests`
node-tests = ["daemon"]
# enable the optional dependencies
daemon = [
  "dep:ibc-chain-registry",
  "dep:tokio",
  "dep:tonic",
  "dep:cosmrs",
  "dep:cw-orch-daemon",
]
eth = ["daemon", "dep:snailquote"]

[dependencies]
# Default deps
cw-orch-contract-derive = { path = "../packages/cw-orch-contract-derive", version = "0.13.3" }
cw-orch-fns-derive = { path = "../packages/cw-orch-fns-derive", version = "0.13.3" }

cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
schemars = "0.8.10"
log = "0.4.14"
serde_json = "1.0.79"
thiserror = { version = "1.0.21" }

# Daemon deps
sha256 = { version = "1.1.1" }
cw-orch-daemon = { path = "../cw-orch-daemon", optional = true }
ibc-chain-registry = { version = "0.24.1", optional = true }
ibc-relayer-types = { version = "0.24.1", optional = true }
tokio = { version = "1.4", features = ["full"], optional = true }
cosmrs = { version = "0.14.0", features = [
  "dev",
  "cosmwasm",
  "grpc",
], optional = true }

# Live mock deps
tonic = { version = "0.9.2", optional = true, features = ["tls", "tls-roots"] }

# Ethereum deps
snailquote = { version = "0.3.1", optional = true }

[dev-dependencies]
cw-orch = { features = ["daemon"], path = "." }
uid = "0.1.7"
env_logger = "0.10.0"
cw20 = { git = "https://github.com/AbstractSDK/cw-plus.git" }
cw20-base = { git = "https://github.com/AbstractSDK/cw-plus.git" }
cosmwasm-schema = "1.2"
tokio-test = "0.4.2"
speculoos = "0.11.0"
ctor = "0.2.0"
duct = "0.13"
counter-contract = { path = "../contracts/counter", features = ["interface"] }
mock-contract = { path = "../contracts/mock_contract", features = [
  "interface",
] }
mock-contract-u64 = { path = "../contracts/mock_contract_u64", features = [
  "interface",
] }
serial_test = "2.0.0"
ibc-relayer-types = { version = "0.24.1" }

# Ethereum deps
ethers-signers = { version = "2.0.7" }
ethers-core = { version = "2.0.7" }
