[package]
name = "cw-orch-contract-cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-cli-derive = { path = "../cw-orch-cli-derive" }
thiserror = { workspace = true }
inquire = { version = "0.6" }
cw-orch = { path = "../../cw-orch", features = ["daemon"] }
cw-orch-cli = { path = "../../cw-orch-cli" }

strum = { version = "0.24", features = ["derive"] }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
