[package]
name = "cw-orch-neutron-test-tube"
version = "0.1.0"
description = "Cw-orch environment adapter for neutron-test-tube"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Test Tube env deps
neutron-test-tube = { workspace = true }

prost-types = { workspace = true }
prost = { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
cw-orch-core = { workspace = true }
cw-orch-mock = { workspace = true }
cw-orch-traits = { workspace = true }

[dev-dependencies]
counter-contract = { path = "../../contracts/counter" }
env_logger = "0.11.3"

cw-orch = { workspace = true }
