[package]
name = "cw-orch-cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
directories = "5.0.1"
keyring = "2.0.5"
cosmrs = { version = "0.15.0", features = ["cosmwasm"] }
rand_core = { version = "0.6", features = ["std"] }
base64 = { version = "0.21.0" }                                             # TODO: move to workspace
cosmwasm-std = { version = "1.3" }
cw-utils = "1.0.3"
cw-orch = { path = "../../cw-orch", features = ["daemon"] }
cw-orch-cli-derive = { path = "../cw-orch-cli-derive", version = "0.13.3" }
cw20 = { workspace = true }
interactive-clap = "0.2.4"
interactive-clap-derive = "0.2.4"
clap = { version = "4.0.18", features = ["derive"] }
color-eyre = { version = "0.6" }
inquire = { version = "0.6" }
strum = { version = "0.24", features = ["derive"] }
bip32 = { version = "0.5", features = ["mnemonic"] }
dotenv = { version = "0.15.0" }

serde_json = "1.0.79"
serde = { workspace = true }
log = "0.4.14"
shell-words = "1.0.0"

tonic = "0.10.0"
derive_more = "0.99"

cw-ownable = { version = "0.5.1" }
