[book]
authors      = ["CyberHoward", "Riada"]
language     = "en"
multilingual = false
src          = "src"
title        = "cw-orchestrator documentation"

[preprocessor.keeper]
command      = "mdbook-keeper"
externs      = ["cosmwasm_schema", "cosmwasm_std", "counter_contract", "cw_orch_interchain", "anyhow"]
manifest_dir = "../"

[output.html]
curly-quotes         = true
default-theme        = "light"
edit-url-template    = "https://github.com/AbstractSDK/cw-orchestrator/edit/main/docs/{path}"
git-repository-icon  = "fa-github"
git-repository-url   = "https://github.com/AbstractSDK/cw-orchestrator"
preferred-dark-theme = "navy"

[extern]
# Define the external crate and its features
cw-orch-interchain = { path = "../cw-orch-interchain", features = ["daemon"] }
