[package]
name = "cw-orch-clone-testing"
version = "0.7.0-alpha.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Adapter for interacting with cw-multi-test via the cw-orchestrator tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }

# This package depends on published cw-orch version due to the clone-testing-cw-multi-test dependency
cw-orch-core = { version = "2.0.0" }
cw-orch-mock = { version = "0.24.0" }
cw-orch-daemon = { version = "0.25.0" }

# clone-cw-multi-test = { version = "0.6.0-alpha.1" }
clone-cw-multi-test = { git = "https://github.com/AbstractSDK/cw-multi-test-fork", branch = "nicolas/orc-161-re-use-contracts-wasm-compilation" }


cw-utils = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
itertools = "0.12.0"
sha2 = "0.10.8"
tonic = { workspace = true }

[dev-dependencies]
cosmwasm-schema = "2.0.0"
speculoos = { workspace = true }

cw20 = { package = "cw20", version = "2.0.0" }
cw20-base = { package = "cw20-base", version = "2.0.0" }

env_logger = "0.10.0"
counter-contract = { path = "../../contracts-ws/contracts/counter" }
# This package depends on published cw-orch version due to the clone-testing-cw-multi-test dependency
cw-orch = { version = "0.25", features = ["daemon"] }
pretty_env_logger = "0.5.0"
