[package]
name = "cw-orch-clone-testing"
version = "0.7.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Adapter for interacting with cw-multi-test via the cw-orchestrator tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }

cw-orch-core = { workspace = true }
cw-orch-daemon = { workspace = true }

clone-cw-multi-test = { version = "0.6.1" }

cw-utils = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
itertools = "0.12.0"
sha2 = "0.10.8"
tonic = { workspace = true }

[dev-dependencies]
cosmwasm-schema = "2.0.0"
speculoos = { workspace = true }

cw20 = { version = "2.0.0" }
cw20-base = { version = "2.0.0" }

env_logger = "0.10.0"
counter-contract = { path = "../../contracts-ws/contracts/counter" }
cw-orch = { path = "../../cw-orch", features = ["daemon"] }
pretty_env_logger = "0.5.0"
