name: GH Pages Deploy

on:
  push:
    branches: [main]
    paths:
      - "docs/**"

  pull_request:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup | Rust
        id: rustup
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Install dependencies 🔧
        run: make install

      - name: Build 🏗️
        run: make build

      - name: Deploy to GitHub Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book