permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: test
env:
  CODECOV_TOKEN: 62fac3fe-498a-4449-a00d-a9b30b443acf
jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [
            stable, # beta failing to some crate using multiple `thread::set_current`
          ]
      fail-fast: false # beta may fail we shouldn't care
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      # https://twitter.com/jonhoo/status/1571290371124260865
      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets
      - name: cargo test network config
        run: |
          cp cw-orch-daemon/tests/mock_networks.toml ~/.cw-orchestrator/networks.toml
          cargo test --package cw-orch-daemon --lib -- network_config::test --ignored

  docs:
    runs-on: ubuntu-latest
    name: doc-tests / stable
    strategy:
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo test --doc
        run: cargo test --doc --locked --all-features
