[package]
name = "counter-contract"
version = "0.11.0"
description = "counter constract"
keywords = ["cosmwasm", "blockchain"]
edition = { workspace = true }

exclude = [".env"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export = []
interface = ["dep:cw-orch"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = "1.0"
cw2 = "1.0"
cosmwasm-schema = "1.2"
schemars = "0.8.10"
thiserror = { version = "1.0.21" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.79"
log = "0.4.14"

cw-orch = { path = "../../cw-orch", optional = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
counter-contract = { path = ".", features = ["interface"] }
